name: Continuous Integration
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Start containers
        run: docker-compose up --detach minio mongo

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -PignoreCheckFailures=true -PcustomProp=myProp -PgithubActor=${{ github.actor }} -PgithubToken=${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop containers
        if: always()
        run: docker-compose down

      - name: Test Report
        uses: scacap/action-surefire-report@v1.0.9
        with:
          report_paths: ./build/test-results/test/*.xml